name: 3d_cattle_demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - opencv  # includes OpenEXR support on conda-forge
  - jupyterlab   # optional, for running notebooks
  - openexr-python
  - imath
  - pip: 
    - "huggingface_hub[cli,xet]"
    # fix hf dependency to include xet
